# Generated by Django 6.0.2 on 2026-02-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetask',
            name='track',
            field=models.CharField(choices=[('career', 'Career'), ('education', 'Education'), ('health', 'Health & Mindset')], default='career', max_length=20),
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routinetask',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
